#!/usr/bin/env node
// Minimal Node runner for Builder Agent skill.
// Accepts --task-json '{...}' and writes a patch file to outgoing_patches/

const fs = require('fs');
const path = require('path');

const OUT_DIR = path.join(__dirname, 'outgoing_patches');
if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

function makePlan(task) {
  const goal = task.goal || '(no goal provided)';
  const targets = task.targets || [];
  let lines = ['Plan:', `Goal: ${goal}`];
  if (targets.length) {
    lines.push('Targets:');
    for (const t of targets) lines.push(` - ${t}`);
  }
  lines.push('Steps:');
  lines.push(' 1) Inspect files');
  lines.push(' 2) Run linters/tests if requested');
  lines.push(' 3) Create minimal patch(es)');
  return lines.join('\n');
}

function createPatch(content) {
  const name = `patch-${Math.random().toString(16).slice(2,10)}.patch`;
  const p = path.join(OUT_DIR, name);
  fs.writeFileSync(p, content, { encoding: 'utf8' });
  return p;
}

function run(task) {
  const plan = makePlan(task);
  const summary = `Planned task: ${task.goal || 'no goal'}`;
  const patchContent = `# Patch generated by Builder Agent (node)\n# Summary: ${summary}\n\n${plan}\n`;
  const patchPath = createPatch(patchContent);
  return { status: 'success', summary, plan, artifacts: [patchPath] };
}

function main() {
  const argv = process.argv.slice(2);
  let jsonArg = null;
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--task-json' && i + 1 < argv.length) {
      jsonArg = argv[i + 1];
      break;
    }
  }
  if (!jsonArg) {
    console.error('Provide --task-json "{...}"');
    process.exit(2);
  }
  let task;
  try {
    task = JSON.parse(jsonArg);
  } catch (e) {
    console.error('Invalid JSON for --task-json');
    process.exit(2);
  }
  const result = run(task);
  console.log(JSON.stringify(result, null, 2));
}

if (require.main === module) main();
