"""Minimal runner for the Builder Agent skill.

This module exposes a `run(task: dict) -> dict` function and a simple CLI.
It is intentionally conservative: it does not modify project files directly.
Instead it writes patch files to `outgoing_patches/` and returns their paths.
"""
import json
import os
import sys
import uuid
from typing import Dict

BASE_DIR = os.path.dirname(__file__)
OUT_DIR = os.path.join(BASE_DIR, "outgoing_patches")

os.makedirs(OUT_DIR, exist_ok=True)


def make_plan(task: Dict) -> str:
    goal = task.get("goal", "(no goal provided)")
    targets = task.get("targets", [])
    lines = ["Plan:", f"Goal: {goal}"]
    if targets:
        lines.append("Targets:")
        for t in targets:
            lines.append(f" - {t}")
    lines.append("Steps:")
    lines.append(" 1) Inspect files")
    lines.append(" 2) Run linters/tests if requested")
    lines.append(" 3) Create minimal patch(es)")
    return "\n".join(lines)


def create_patch(content: str) -> str:
    name = f"patch-{uuid.uuid4().hex[:8]}.patch"
    path = os.path.join(OUT_DIR, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path


def run(task: Dict) -> Dict:
    plan = make_plan(task)
    summary = f"Planned task: {task.get('goal', 'no goal')}"
    # Create a stub patch describing the plan
    patch_content = f"# Patch generated by Builder Agent\n# Summary: {summary}\n\n{plan}\n"
    patch_path = create_patch(patch_content)
    return {
        "status": "success",
        "summary": summary,
        "plan": plan,
        "artifacts": [patch_path],
    }


def _cli_main():
    import argparse

    p = argparse.ArgumentParser(description="Run Builder Agent task")
    group = p.add_mutually_exclusive_group(required=True)
    group.add_argument("--task-file", help="Path to JSON task file")
    group.add_argument("--task-json", help="Task JSON string")
    args = p.parse_args()
    if args.task_file:
        raw = open(args.task_file, "r", encoding="utf-8").read()
    else:
        raw = args.task_json
    task = json.loads(raw)
    result = run(task)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    _cli_main()
